### ISSUE TITLE
HU aanpassingen

### ISSUE THREAD

**Issue by peterdubbeldsurf** [surfedushare/harvester#404]
**TODO:**

- [x] proefkoppeling opzetten met de acceptatie api van de HU om te testen
- [ ] testen en feedback verzamelen op basis van de proefkoppeling (hoe komt de data binnen, wat gaat er niet goed en hoe kunnen we dat oplossen)
- [ ] aanpassingen maken waar nodig (bij de HU, of bij Fako)
- [ ] definitieve koppeling maken na goedkeuring

Hierbij de benodigde informatie die ik (imko) vanuit Creates ontvangen heb.

De verbinding is als volgt: Omgeving: acceptatie.hu.nl of www.hu.nl Paden: • /api/publinova/persons • /api/publinova/products • /api/publinova/projects Header: apiKey

Bijvoorbeeld: Invoke-WebRequest -Uri https://acceptatie.hu.nl/api/publinova/projects -Headers @{ "Accept" = "application/json"; "apiKey" = "HIER_KOMT_DE_APIKEY" } -OutFile projects.json

De API key hebben jullie als het goed is.

Qua documentatie hebben wij gebruik gemaakt van jullie requirements/documentatie.

**De API keys voor ACC en PRD zijn in de lastpass vault opgeslagen.**

**Comment by fako** [comment]
Take into consideration: https://git.ia.surfsara.nl/publinova/tech/-/issues/1380

**Comment by fako** [comment]
Er zijn een aantal dingen die opvallen

In het algmeen:
- [ ] Alles komt door via 1 response. Deze duurt 14s voor projecten. Dit gaat niet heel lang opschalen. Pagination is aan te raden.
- [ ] Er komen geen email adressen door (op geen enkele plek). Dat is volgens mij een probleem als mensen willen inloggen en wijzigingen doorvoeren.
- [ ] Wat moet de naam zijn van HU? Op dit moment is het "HU" (zij geven naam door via projecten) en niet "Hogeschool Utrecht"

Bij personen:
- [ ] is_employed is altijd null. Volgens mij is dat goed, maar dat is wel iets om op te letten (dat dit inderdaad goed gaat)

Bij projecten:
- [ ] Er zijn geen owners. Ik heb nu de contacts de owners gemaakt. 
- [ ] photo_url wordt wel doorgegeven, maar dat veld bestaat niet voor projecten
- [ ] projecten hebben alleen een titel qua tekst en daarmee krijg je hele lege project pagina's
- [ ] Eind datum ligt soms voor de start datum. Voorbeeld: 1cd33732-7513-4004-9486-aa2d8f38215f
- [ ] Sommige projecten zijn nooit begonnen. Voorbeeld: fb71e2f9-f009-488b-aa1f-2b345ec91bec

**Comment by fako** [comment]
@mlagerwerf @peterdubbeldsurf we kunnen weer een aantal dingen afstemmen met HU.
Zie uitkomsten via:
- https://sources.dev.publinova.nl/api/v1/entities/persons/hu/
- https://sources.dev.publinova.nl/api/v1/entities/projects/hu/

**Comment by fako** [comment]
HU will make adjustments after that a new ticket will be created on the new board
